import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Camera, Check, ChevronDown, CircleHelp, Info, KeyRound, LogOut, Moon, Palette, Save, ShieldAlert, Sun, Trash2, Upload, UserRound } from "lucide-react";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../auth";
import { api, formatDate, message } from "../lib";
import type { User } from "../types";
import { Avatar, Button, Card, Field, PageHeader } from "../ui";

export function Profile() {
  const {user,setUser}=useAuth();const queryClient=useQueryClient();const fileRef=useRef<HTMLInputElement>(null);
  const [edit,setEdit]=useState(false);const [form,setForm]=useState({displayName:user!.displayName,email:user!.email,phone:user!.phone??"",timeZone:user!.timeZone});const [error,setError]=useState("");
  const save=async()=>{setError("");try{const updated=await api<User>("/profile",{method:"PATCH",body:JSON.stringify({...form,phone:form.phone||null})});setUser({...user!,...updated});setEdit(false);}catch(e){setError(message(e));}};
  const upload=async(file?:File)=>{if(!file)return;const data=new FormData();data.append("file",file);try{const result=await api<{profileImageUrl:string}>("/profile/photo",{method:"POST",body:data});setUser({...user!,profileImageUrl:result.profileImageUrl});}catch(e){setError(message(e));}};
  const remove=async()=>{await api("/profile/photo",{method:"DELETE"});setUser({...user!,profileImageUrl:null});};
  const cancel=()=>{setForm({displayName:user!.displayName,email:user!.email,phone:user!.phone??"",timeZone:user!.timeZone});setEdit(false);};
  return <div className="page"><PageHeader eyebrow="Your account" title="Profile" description="The details people see when you’re in the room." action={!edit&&<Button onClick={()=>setEdit(true)}><UserRound/> Edit profile</Button>}/>
    {error&&<div className="alert">{error}</div>}<div className="profile-grid"><Card className="profile-card"><div className="avatar-wrap"><Avatar size="lg" name={user!.displayName} src={user!.profileImageUrl}/><button aria-label="Change profile photo" onClick={()=>fileRef.current?.click()}><Camera/></button><input ref={fileRef} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>void upload(e.target.files?.[0])}/></div><h2>{user!.displayName}</h2><span className="role-badge">{user!.role==="ADMIN"?"Meetup admin":"Participant"}</span><p>{user!.email}</p><div className="photo-actions"><Button variant="secondary" onClick={()=>fileRef.current?.click()}><Upload/> {user!.profileImageUrl?"Replace":"Upload"}</Button>{user!.profileImageUrl&&<Button variant="ghost" onClick={()=>void remove()}>Remove</Button>}</div><small>JPEG, PNG or WebP. Keep it under the server upload limit.</small></Card>
    <Card><div className="card-head"><div><h2>Personal information</h2><p>Saved changes apply everywhere immediately.</p></div></div><div className="form-grid"><Field label="Display name"><input disabled={!edit} value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></Field><Field label="Email"><input disabled={!edit} type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Phone (optional)"><input disabled={!edit} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="Time zone"><input disabled={!edit} value={form.timeZone} onChange={e=>setForm({...form,timeZone:e.target.value})}/></Field></div><div className="zone-preview"><strong>Time preview</strong><span>{formatDate(new Date(),form.timeZone,"full")}</span><small>Changing zone changes display and future date entry only. Stored meetup instants do not move.</small></div>{edit&&<div className="actions"><Button variant="secondary" onClick={cancel}>Cancel</Button><Button onClick={()=>void save()} disabled={!form.displayName||!form.email||!form.timeZone}><Save/> Save changes</Button></div>}<hr/><dl className="detail-list"><div><dt>Member since</dt><dd>{formatDate(user!.createdAt,user!.timeZone)}</dd></div><div><dt>Account role</dt><dd>{user!.role}</dd></div></dl></Card></div>
  </div>;
}
export function Settings() {
  const {user,setUser,logout}=useAuth();const navigate=useNavigate();const [password,setPassword]=useState({current:"",next:"",confirm:""});const [deleteForm,setDeleteForm]=useState({password:"",confirmation:""});const [notice,setNotice]=useState("");const [error,setError]=useState("");
  const theme=async(value:"LIGHT"|"DARK"|"SYSTEM")=>{setUser({...user!,theme:value});try{await api("/profile",{method:"PATCH",body:JSON.stringify({theme:value})});}catch(e){setError(message(e));}};
  const changePassword=async(e:FormEvent)=>{e.preventDefault();if(password.next!==password.confirm)return setError("New passwords do not match.");try{const r=await api<{message:string}>("/auth/change-password",{method:"POST",body:JSON.stringify({currentPassword:password.current,newPassword:password.next})});setNotice(r.message);setPassword({current:"",next:"",confirm:""});}catch(e){setError(message(e));}};
  const deleteAccount=async(e:FormEvent)=>{e.preventDefault();if(!confirm("This permanently deletes your account. Continue?"))return;try{await api("/profile",{method:"DELETE",body:JSON.stringify(deleteForm)});setUser(null);navigate("/login",{replace:true});}catch(err){setError(message(err));}};
  return <div className="page settings-page"><PageHeader eyebrow="Preferences" title="Settings" description="Make MeetCon feel right for you."/>
    {(error||notice)&&<div className={error?"alert":"success-box"}>{error||notice}</div>}<Card><div className="settings-title"><Palette/><div><h2>Appearance</h2><p>Applied instantly on this device and saved to your profile.</p></div></div><div className="theme-grid">{([["LIGHT",Sun,"Light"],["DARK",Moon,"Dark"],["SYSTEM",Palette,"System"]] as const).map(([value,Icon,label])=><button key={value} className={user!.theme===value?"active":""} onClick={()=>void theme(value)}><span className={`theme-preview ${value.toLowerCase()}`}><Icon/></span><strong>{label}</strong>{user!.theme===value&&<Check/>}</button>)}</div></Card>
    <Card><div className="settings-title"><KeyRound/><div><h2>Change password</h2><p>Other signed-in sessions will be revoked.</p></div></div><form onSubmit={changePassword} className="form-grid"><Field label="Current password"><input type="password" value={password.current} onChange={e=>setPassword({...password,current:e.target.value})} required/></Field><Field label="New password" hint="12+ characters, mixed case and a number"><input type="password" value={password.next} onChange={e=>setPassword({...password,next:e.target.value})} required/></Field><Field label="Confirm new password"><input type="password" value={password.confirm} onChange={e=>setPassword({...password,confirm:e.target.value})} required/></Field><div><Button>Update password</Button></div></form></Card>
    <div className="settings-links"><Link to="/help"><CircleHelp/><div><strong>Help center</strong><span>Answers for common questions</span></div></Link><Link to="/about"><Info/><div><strong>About MeetCon</strong><span>Version and privacy summary</span></div></Link><button onClick={()=>void logout()}><LogOut/><div><strong>Log out</strong><span>End this browser session</span></div></button></div>
    <Card className="danger-zone"><div className="settings-title"><ShieldAlert/><div><h2>Delete account</h2><p>{user!.role==="ADMIN"?"Future meetups will be cancelled. Completed history stays anonymized.":"Historical answers remain only as anonymous totals."}</p></div></div><form onSubmit={deleteAccount} className="form-grid"><Field label="Current password"><input type="password" value={deleteForm.password} onChange={e=>setDeleteForm({...deleteForm,password:e.target.value})} required/></Field><Field label='Type "DELETE" to confirm'><input value={deleteForm.confirmation} onChange={e=>setDeleteForm({...deleteForm,confirmation:e.target.value})} required/></Field><div><Button variant="danger" disabled={deleteForm.confirmation!=="DELETE"}><Trash2/> Delete my account</Button></div></form></Card>
  </div>;
}
const helpSections: [string,string][]=[["Creating and joining","Admins create a schedule and four-option questions, then share a code, link or QR. Participants can join by any shared invitation."],["How timing works","The server divides the meetup duration equally across questions. Your countdown stays synchronized with server time."],["Permanent answers","A submitted choice is final. This keeps live results fair and prevents changes after seeing participation."],["Connectivity","If you go offline, MeetCon keeps the current screen visible and resynchronizes when you reconnect."],["Account support","Use Forgot Password on the sign-in screen. For additional support, contact your MeetCon workspace administrator."]];
export function Help(){const [search,setSearch]=useState("");return <div className="page narrow"><PageHeader eyebrow="Support" title="How can we help?" description="Quick answers for a smooth meetup."/><input className="help-search" placeholder="Search help…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="help-list">{helpSections.filter(([a,b])=>(a+b).toLowerCase().includes(search.toLowerCase())).map(([title,text])=><details key={title}><summary>{title}<ChevronDown/></summary><p>{text}</p></details>)}</div></div>}
export function About(){return <div className="page narrow"><PageHeader eyebrow="About" title="MeetCon" description="Every voice, right on time."/><Card className="about-card"><span className="logo-mark"><Info/></span><h2>MeetCon Web</h2><p>Version 1.0.0 · React 19</p><p>MeetCon stores only the account and response information needed to operate timed meetups. Participant choices are visible to the owning administrator; live participant views never reveal competing option counts or names.</p><p>Terms and privacy links will appear here when supplied by your organization.</p></Card></div>}
